### ISSUE TITLE
Possible improvements on the code examples

### ISSUE THREAD

**Issue by jonniebigodes** [andre-brdoch/learnstorybook-v6-vue#1]
Hi @andre-brdoch , like i've mentioned i've forked your repo and gone over it over during the weekend. While checking it one thing caught my eye. The way you're using the actions [here](https://github.com/andre-brdoch/learnstorybook-v6-vue/blob/master/src/components/1-simple-component/Task.stories.js#L11-L20) might get us into a bit of trouble further down the line. Starting at the composite component. As we'll need access to the actions and we would need to extract them into a new variable and export it, just like what's currently in the tutorial [here](https://www.learnstorybook.com/intro-to-storybook/vue/en/simple-component/) and [here](https://www.learnstorybook.com/intro-to-storybook/vue/en/composite-component/).  What we could do is the following:
- Starting with the Task component
```html
<template>
  <div :class="taskClass">
    <label class="checkbox">
      <input
        type="checkbox"
        :checked="isChecked"
        :disabled="true"
        name="checked"
      />
      <span class="checkbox-custom" @click="onArchiveTask" />
    </label>
    <div class="title">
      <input
        type="text"
        :readonly="true"
        :value="this.task.title"
        placeholder="Input title"
      />
    </div>
    <div class="actions">
      <a v-if="!isChecked">
        <span class="icon-star" @click="onPinTask" />
      </a>
    </div>
  </div>
</template>

<script>
export default {
  name: "task",
  props: {
    task: {
      type: Object,
      required: true,
      default: () => ({
        id: "",
        state: "",
        title: "",
      }),
      validator: task => ["id", "state", "title"].every(key => key in task)
    },
  },
  computed: {
    taskClass() {
      return `list-item ${this.task.state}`;
    },
    isChecked() {
      return this.task.state === "TASK_ARCHIVED";
    },
  },
  methods: {
    onArchiveTask() {
      this.$emit("onArchiveTask",this.$props.task.id);
    },
    onPinTask() {
      this.$emit("onPinTask",this.$props.task.id);
    },
  },
};
</script>
```
- And the Task story file would be something like:
```js
import Task from "./Task.vue";

export default {
  component: Task,
  title: "Task"
};

const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { Task },
  template:
    '<task :task="task" @onPinTask="onPinTask" @onArchiveTask="onArchiveTask" />'
});

export const Default = Template.bind({});
Default.args = {
  task: {
    id: "1",
    title: "Test Task",
    state: "TASK_INBOX",
    updatedAt: new Date(2018, 0, 1, 9, 0)
  }
};

export const Pinned = Template.bind({});
Pinned.args = {
  task: {
    ...Default.args.task,
    state: "TASK_PINNED"
  }
};

export const Archived = Template.bind({});
Archived.args = {
  task: {
    ...Default.args.task,
    state: "TASK_ARCHIVED"
  }
};

```

With this we would leave `.storybook/preview.js` file almost untouched. As the only change would be to include the css for the app and nothing more, turning it into:
```js
import '../src/index.css';
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
}
```

Then when we reach the composite component section the starter `TaskList.vue` would be something like:
```html
<template>
  <div>
    <div class="list-items" v-if="loading">loading</div>
    <div class="list-items" v-if="noTasks && !loading">empty</div>
    <div class="list-items" v-if="showTasks">
      <task
        v-for="(task, index) in tasks"
        :key="index"
        :task="task"
        @onPinTask="onPinTask"
        @onArchiveTask="onArchiveTask"
      />
    </div>
  </div>
</template>

<script>
import Task from "./Task";
export default {
  name: "task-list",
  props: {
    loading: {
      type: Boolean,
      default: false,
    },
    tasks: {
      type: Array,
      default: () => [],
    },
  },
  components: {
    Task,
  },
  computed: {
    noTasks() {
      return this.tasks.length === 0;
    },
    showTasks() {
      return !this.loading && !this.noTasks;
    },
  },
  methods: {
    onArchiveTask(event) {
      this.$emit("onArchiveTask", event);
    },
    onPinTask(event) {
      this.$emit("onPinTask", event);
    },
  },
};
</script>
```

And the `TaskList.stories.js` file would look like this:
```js
import TaskList from "./TaskList.vue";
import * as TaskStories from "./Task.stories";
export default {
  component: TaskList,
  title: "TaskList",
  decorators: [() => ({ template: '<div style="margin: 3em;"><story/></div>' })]
};

const Template = (args, { argTypes }) => ({
  components: { TaskList },
  props: Object.keys(argTypes),
  template:
    '<task-list :tasks="tasks" @onArchiveTask="onArchiveTask" @onPinTask="onPinTask" v-bind="$props"/>',
});

export const Default = Template.bind({});
Default.args = {
  tasks: [
    { ...TaskStories.Default.args.task, id: "1", title: "Task 1" },
    { ...TaskStories.Default.args.task, id: "2", title: "Task 2" },
    { ...TaskStories.Default.args.task, id: "3", title: "Task 3" },
    { ...TaskStories.Default.args.task, id: "4", title: "Task 4" },
    { ...TaskStories.Default.args.task, id: "5", title: "Task 5" },
    { ...TaskStories.Default.args.task, id: "6", title: "Task 6" },
  ],
};

export const WithPinnedTasks = Template.bind({});
WithPinnedTasks.args = {
  tasks: [
    ...Default.args.tasks.slice(0, 5),
    { id: "6", title: "Task 6 (pinned)", state: "TASK_PINNED" },
  ],
};

export const Loading = Template.bind({});
Loading.args = {
  tasks: [],
  loading: true,
};

export const Empty = Template.bind({});
Empty.args = {
  // Shaping the stories through args composition.
  // Inherited data coming from the Loading story.
  ...Loading.args,
  loading: false,
};
```

It's kinda of a trade off at the expense of the component versus the stories file. But as it's an intro to storybook tutorial i would rather keep the stories file leaner and simpler to the reader. But we have room for improvement here. Love to hear your thoughts on this.

Stay safe.

**Comment by andre-brdoch** [comment]
Hi Jonnie, thank you so much for taking the time to review! 

That is true, thanks for pointing that out. The problem is, that in Vue event names should be [kebab-cased](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names). With that restriction, I could not come up with a way of utilizing the new ways of dealing with actions:
- using actions parameter: Will throw an error that the handler is not defined
- using argTypes: possible, but then we would also need to hide it from the ArgsTable. Also it might be misleading, since in vue we dont pass functions as props, but use events instead. Adding the handlers to argTypes could be misunderstood as passing them as props.

Because of this, I instead did it like it is was done with the current vue examples, defining the actions as methods and making them exportable. Do you think that is fine? 

Also, please note that in `Task.vue` I kept the event emits inline, instead of adding methods. This is because the stories also include `onPinTask` and `onArchiveTask` methods, and it might have been confusing to which one it refers.

I went ahead and added the rest of the intro. Looking forwards to hearing your toughts 😃 If you want I could also add the custom addon chapter. I skipped it for now since it was missing in the current vue chapter, I assume that is because it mixes with React.

**Comment by jonniebigodes** [comment]
@andre-brdoch just ran through the latest code version and it looks awesome, really. Thank you for the time and effort you've put into this. It really is a great help to the tutorial. If you want to do the honors, i'm more than ok with you updating the vue tutorial as it's basically complete based on the code we have. Let me know.

Regarding your feedback. I understand what you mean, i was aiming for a simple approach and keep the implementation short and sweet, but it's how vue is setup and wants us to follow... I'm good with the approach.

Stay safe

**Comment by andre-brdoch** [comment]
Awesome, thanks for reviewing, I will update the docs in the next few days 😄 take care!

**Comment by andre-brdoch** [comment]
@jonniebigodes Sorry that it took me so long, but the PR is ready now!
https://github.com/chromaui/learnstorybook.com/pull/405
Have a good day!
