### ISSUE TITLE
Issue with tests

### ISSUE THREAD

**Issue by jonniebigodes** [andre-brdoch/learnstorybook-v6-vue#3]
While checking this one item was missing from my end and i'm truly sorry for that. I scoped the code out in terms of Storybook and with that "flew past" (pardon the bad pun) the testing parts with Jest.  And that's why i'm raising the issue. As is here and in your [pull request](https://github.com/chromaui/learnstorybook.com/pull/405) in the LearnStorybook repo when the reader reaches the Unit tests with Jest section in the Composite component chapter, he/she will hit a snag. As the test is not run. Based on my testing i'm inclined to believe that it's a Vue thing. How it's currently organizing unit test files.

If you're ok, move the the following [file](https://github.com/andre-brdoch/learnstorybook-v6-vue/blob/master/src/components/3-list-states/TaskList.spec.js) to `tests/unit` and it will run.

One extra item regarding the test used, how you're currently implementing it:
```js
import Vue from "vue";
import { WithPinnedTasks } from "./TaskList.stories";

it("renders pinned tasks at the start of the list", () => {
  // render WithPinnedTasks story
  const Constructor = Vue.extend(WithPinnedTasks);
  const vm = new Constructor({
    propsData: WithPinnedTasks.args
  }).$mount();
  const firstTaskPinned = vm.$el.querySelector(
    ".list-item:nth-child(1).TASK_PINNED"
  );

  // We expect the pinned task to be rendered first, not at the end
  expect(firstTaskPinned).not.toBe(null);
});
````

Once that is done, we'll encounter the following issue with `yarn test:unit`. It will generate the following error:

```shell
console.log tests/unit/TaskList.spec.js:8
      WithPinnedTasks args=>{"tasks":[{"id":"1","title":"Task 1","state":"TASK_INBOX","updatedAt":"2018-01-01T09:00:00.000Z"},{"id":"2","title":"Task 2","state":"TASK_INBOX","updatedAt":"2018-01-01T09:00:00.000Z"},{"id":"3","title":"Task 3","state":"TASK_INBOX","updatedAt":"2018-01-01T09:00:00.000Z"},{"id":"4","title":"Task 4","state":"TASK_INBOX","updatedAt":"2018-01-01T09:00:00.000Z"},{"id":"5","title":"Task 5","state":"TASK_INBOX","updatedAt":"2018-01-01T09:00:00.000Z"},{"id":"6","title":"Task 6 (pinned)","state":"TASK_PINNED"}]}
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Invalid component name: "bound Template". Component names should conform to valid custom element name in html5 specification.

  ● renders pinned tasks at the start of the list

    TypeError: Cannot read property 'props' of undefined

       8 |   console.log(`WithPinnedTasks args=>${JSON.stringify(WithPinnedTasks.args)}`);
       9 |   // render WithPinnedTasks story
    > 10 |   const Constructor = Vue.extend(WithPinnedTasks);
         |                           ^
      11 |   // const Constructor = Vue.extend(TaskList);
      12 |   const vm = new Constructor({
      13 |     propsData: WithPinnedTasks.args,

      at normalizeProps (node_modules/vue/dist/vue.runtime.common.dev.js:1419:23)
      at mergeOptions (node_modules/vue/dist/vue.runtime.common.dev.js:1521:3)
      at Function.extend (node_modules/vue/dist/vue.runtime.common.dev.js:5139:19)
      at Object.<anonymous> (tests/unit/TaskList.spec.js:10:27)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)

 PASS  tests/unit/storybook.spec.js

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   7 passed, 7 total
````

(Ignore the console.log, i was checking something else :P)

The actual test should be the following:
```js
import Vue from "vue";
import PureTaskList from "../../src/components/PureTaskList.vue"; 
import { WithPinnedTasks } from "../../src/components/PureTaskList.stories"; 

it("renders pinned tasks at the start of the list", () => {
  // render WithPinnedTasks story
  const Constructor = Vue.extend(PureTaskList); //<-- uses the component for the actual test as opposed the Template in the story file
  const vm = new Constructor({
    propsData: WithPinnedTasks.args, // <-- uses the data incoming from the stories file
  }).$mount();
  const firstTaskPinned = vm.$el.querySelector(
    ".list-item:nth-child(1).TASK_PINNED"
  );

  // We expect the pinned task to be rendered first, not at the end
  expect(firstTaskPinned).not.toBe(null);
});

```

With react the test would run without any issues by importing the story into the test. But with Vue and Storybook, there's a lot going on "under the hood" (pardon the bad pun), i wish we could use the same approach, but currently it's not possible. With that we'll need to make a small compromise enable testing. 

I'll comment on your pull request linking this issue. Let me know if you're ok with it and we'll go from there. Really stoked to get this version of the tutorial out. And extremely thankful for your time and effort in this.

Also once more, sorry for the fumble fingering on the tests and not approaching you sooner with this.

Stay safe.

**Comment by andre-brdoch** [comment]
Thank you so much for the indepth explanation @jonniebigodes! Really sorry I missed that! Applied the changes to the PR, let me know if it needs more work 👍 

Take care!

**Comment by jonniebigodes** [comment]
@andre-brdoch no problem and no need to be sorry. We're all learning here and sometimes something is missed. I just checked and as soon as you address the changes to branch names (master=>main) i'll merge it. 

Let me know once you applied the changes. 

Stay safe

**Comment by jonniebigodes** [comment]
Going to close this issue as it's now fixed. And with your help(the code hosted here) the vue branch in the learnstorybook-code repo is now updated to the latest version of storybook. 

Once again thank you very much for the support and help. Me personally and the team is really thankful for it.

Stay safe
